"""
Seed content extracted from src/pondr/data.js - keep the two in sync.
ADJECTIVES/CREATURES power the deterministic handle formula
(adjective[n % len] + " " + creature[(n*7) % len]) used for stranger accounts.
"""

ADJECTIVES = ['Brave',
 'Quiet',
 'Gentle',
 'Curious',
 'Kind',
 'Bright',
 'Calm',
 'Bold',
 'Wise',
 'Hopeful',
 'Tender',
 'Steady',
 'Wandering',
 'Lucky',
 'Mellow',
 'Humble',
 'Radiant',
 'Patient',
 'Sleepy',
 'Grumpy',
 'Snazzy',
 'Cosmic',
 'Sassy',
 'Dapper',
 'Cheeky',
 'Plucky',
 'Whimsical',
 'Giddy',
 'Jolly',
 'Zesty',
 'Wobbly',
 'Peppy',
 'Funky',
 'Quirky',
 'Velvet',
 'Drowsy',
 'Witty',
 'Breezy',
 'Sunny',
 'Dreamy',
 'Cuddly',
 'Bouncy',
 'Fuzzy',
 'Spunky',
 'Chipper',
 'Goofy',
 'Dazzling',
 'Glittery',
 'Sparkly',
 'Twinkly',
 'Nifty',
 'Swift',
 'Nimble',
 'Cozy',
 'Snug',
 'Toasty',
 'Spicy',
 'Tangy',
 'Minty',
 'Frosty',
 'Misty',
 'Stormy',
 'Cloudy',
 'Starry',
 'Lunar',
 'Stellar',
 'Galactic',
 'Mythic',
 'Noble',
 'Regal',
 'Stoic',
 'Serene',
 'Placid',
 'Zen',
 'Earnest',
 'Loyal',
 'Trusty',
 'Merry',
 'Cheery',
 'Sprightly',
 'Lively',
 'Vivid',
 'Bubbly',
 'Jaunty',
 'Dashing',
 'Suave',
 'Posh',
 'Fancy',
 'Charming',
 'Graceful',
 'Spry',
 'Perky',
 'Wholesome',
 'Modest',
 'Mighty',
 'Valiant',
 'Fearless',
 'Daring',
 'Curly',
 'Tiny',
 'Grand',
 'Epic',
 'Groovy',
 'Jazzy',
 'Snappy',
 'Crisp',
 'Fresh',
 'Chirpy',
 'Wiggly',
 'Squishy',
 'Fluffy']

CREATURES = ['Otter',
 'Heron',
 'Fox',
 'Sparrow',
 'Whale',
 'Moth',
 'Hare',
 'Finch',
 'Lynx',
 'Robin',
 'Badger',
 'Crane',
 'Wren',
 'Deer',
 'Owl',
 'Seal',
 'Newt',
 'Swan',
 'Platypus',
 'Axolotl',
 'Narwhal',
 'Pufferfish',
 'Hedgehog',
 'Sloth',
 'Quokka',
 'Capybara',
 'Gecko',
 'Jellyfish',
 'Toad',
 'Pangolin',
 'Octopus',
 'Penguin',
 'Raccoon',
 'Possum',
 'Ferret',
 'Weasel',
 'Stoat',
 'Mole',
 'Vole',
 'Shrew',
 'Bison',
 'Moose',
 'Elk',
 'Caribou',
 'Ibex',
 'Tapir',
 'Okapi',
 'Lemur',
 'Loris',
 'Meerkat',
 'Mongoose',
 'Aardvark',
 'Armadillo',
 'Wombat',
 'Wallaby',
 'Koala',
 'Dingo',
 'Kiwi',
 'Kookaburra',
 'Cassowary',
 'Pelican',
 'Puffin',
 'Albatross',
 'Egret',
 'Ibis',
 'Stork',
 'Falcon',
 'Kestrel',
 'Osprey',
 'Magpie',
 'Raven',
 'Crow',
 'Jay',
 'Lark',
 'Swift',
 'Swallow',
 'Starling',
 'Hummingbird',
 'Toucan',
 'Macaw',
 'Parrot',
 'Cockatoo',
 'Flamingo',
 'Peacock',
 'Pheasant',
 'Quail',
 'Grouse',
 'Turtle',
 'Tortoise',
 'Chameleon',
 'Iguana',
 'Skink',
 'Salamander',
 'Frog',
 'Seahorse',
 'Starfish',
 'Urchin',
 'Squid',
 'Cuttlefish',
 'Nautilus',
 'Manta',
 'Stingray',
 'Anglerfish',
 'Pike',
 'Trout',
 'Koi',
 'Eel',
 'Dolphin',
 'Porpoise',
 'Walrus',
 'Manatee',
 'Dugong',
 'Beaver',
 'Chipmunk',
 'Squirrel',
 'Dormouse',
 'Marmot',
 'Hamster',
 'Gerbil',
 'Mantis',
 'Beetle',
 'Ladybug',
 'Firefly',
 'Cricket',
 'Butterfly',
 'Dragonfly',
 'Bumblebee',
 'Snail',
 'Crab',
 'Lobster',
 'Shrimp',
 'Dragon',
 'Phoenix',
 'Unicorn',
 'Griffin',
 'Pegasus',
 'Kraken',
 'Sphinx',
 'Yeti',
 'Wyvern',
 'Hydra',
 'Basilisk',
 'Chimera',
 'Faun',
 'Sprite',
 'Pixie']

PROMPTS = ["What's on your mind right now?",
 "What's something you've been quietly proud of?",
 "What's something you wish you could tell a stranger?",
 "What do you pretend to understand but really don't?",
 "What's a small joy from today?",
 "What's something you're still learning to forgive?",
 'When did you last feel truly at peace?',
 'What would you tell your younger self?',
 "What's a kindness you've never forgotten?",
 'What helped you through a hard week?',
 "What's a comfort you return to again and again?",
 'What are you glad you said out loud?',
 'What does home feel like to you?']

SAMPLE_NOTES = [{'prompt': "What's on your mind right now?",
  'cat': 'Reflection',
  'author': 438,
  'title': "Rest isn't falling behind",
  'body': "I think I'm slowly learning that rest doesn't mean I'm falling behind. It's taken me "
          'years to unlearn the idea that productivity equals worth. Some days the bravest thing I '
          "do is close the laptop, sit by the window, and let the afternoon be quiet. I'm trying "
          "to believe that the world keeps turning even when I'm still."},
 {'prompt': "What's on your mind right now?",
  'cat': 'Hope',
  'author': 1207,
  'title': 'Choosing to keep going',
  'body': "Some days are heavy, but I'm choosing to keep going anyway. Not because I feel strong, "
          "but because tomorrow hasn't happened yet and I want to see who I become on the other "
          "side of this. If you're reading this and you're tired too — let's keep going together."},
 {'prompt': "What's on your mind right now?",
  'cat': 'Confession',
  'author': 89,
  'title': "I pretend I'm fine",
  'body': "I pretend I'm fine so often, even though I just want someone to ask if I'm okay and "
          "actually wait for the real answer. I've gotten so good at the performance that "
          "sometimes I fool myself. But underneath the 'I'm good, thanks' there's a person who "
          'would give anything to be seen for one honest minute.'},
 {'prompt': "What's on your mind right now?",
  'cat': 'Question',
  'author': 3162,
  'title': 'How do you let go?',
  'body': 'How do you let go of something that still means everything to you? I keep waiting for '
          "the day it stops aching, but it just changes shape. Maybe letting go isn't a single "
          "moment — maybe it's a thousand small choices to look forward instead of back. I'm still "
          'learning the first one.'},
 {'prompt': "What's something you've been quietly proud of?",
  'cat': 'Memory',
  'author': 712,
  'title': 'The little things',
  'body': 'I miss the little things about someone I used to talk to every day. The way they texted '
          "in lowercase, how they'd send a song with no caption, the inside jokes that don't make "
          "sense to anyone else. We didn't have a dramatic ending. We just slowly stopped, and "
          'somehow that hurts more.'},
 {'prompt': "What's something you've been quietly proud of?",
  'cat': 'Reflection',
  'author': 2055,
  'title': 'Closed chapters',
  'body': "Not every door is meant to stay open. I'm learning to be okay with closed chapters and "
          "new beginnings, even when I don't get the closure I wanted. Some stories just end "
          'mid-sentence, and the growth is in writing the next page anyway.'},
 {'prompt': "What's something you wish you could tell a stranger?",
  'cat': 'Gratitude',
  'author': 56,
  'title': 'Moments no one sees',
  'body': 'Grateful for the small moments that no one else sees but somehow make everything feel '
          "worth it. The first sip of coffee before the house wakes up. A stranger's dog deciding "
          "I'm worth a tail wag. The particular gold of 5pm light on the kitchen wall. These are "
          "the things I'd miss most."},
 {'prompt': "What's something you wish you could tell a stranger?",
  'cat': 'Confession',
  'author': 1894,
  'title': 'Still crying over it',
  'body': 'I still cry over things that happened months ago, in the shower, in the car, in the gap '
          "between meetings. People think I've moved on because I stopped talking about it. The "
          'truth is I just learned to carry it more quietly.'},
 {'prompt': "What do you pretend to understand but really don't?",
  'cat': 'Hope',
  'author': 327,
  'title': 'Maybe next year',
  'body': "Maybe I'll be different next year. Maybe I'll finally be the person I keep promising "
          "myself I'll become — a little kinder, a little braver, a little less afraid of being a "
          'beginner. Maybe that hope is enough to keep going. Most days, it has to be.'},
 {'prompt': "What do you pretend to understand but really don't?",
  'cat': 'Memory',
  'author': 941,
  'title': 'Rain on hot pavement',
  'body': "The smell of rain on hot pavement still takes me back to my grandmother's porch, the "
          "screen door slapping shut, the radio playing something old. I didn't know those were "
          "the good old days while I was living them. I'd give a lot for one more ordinary "
          'afternoon there.'},
 {'prompt': "What's a small joy from today?",
  'cat': 'Question',
  'author': 2783,
  'title': 'Homesick for nowhere',
  'body': 'Is it normal to feel homesick for a place you never actually lived? Sometimes I ache '
          'for a version of life I only imagined — a small town, a slow morning, people who know '
          "my name at the bakery. Maybe home isn't a place I lost. Maybe it's a place I haven't "
          'built yet.'},
 {'prompt': "What's a small joy from today?",
  'cat': 'Gratitude',
  'author': 604,
  'title': 'To the stranger at the door',
  'body': 'Thank you to the stranger who held the door this morning when my hands were full and my '
          "day was already falling apart. You'll never know that it was the first kind thing that "
          'happened to me in a week, and that it made me cry a little on the train. Small kindness '
          'travels further than you think.'},
 {'prompt': "What's on your mind right now?",
  'cat': 'Reflection',
  'author': 271,
  'title': 'Learning to sit with quiet',
  'body': "I used to fill every silence with noise — podcasts, scrolling, anything. Lately I've "
          "been letting the quiet just be quiet. It's uncomfortable at first, like a room that's "
          "too still, but underneath it there's a version of me I haven't heard from in a long "
          'time.'},
 {'prompt': "What's on your mind right now?",
  'cat': 'Hope',
  'author': 1530,
  'title': 'A softer year',
  'body': "I'm hoping this is the year I stop being so hard on myself. Not all at once — just a "
          "little gentler each day. If I can talk to myself the way I'd talk to a friend, maybe "
          "that's enough of a resolution."},
 {'prompt': "What's on your mind right now?",
  'cat': 'Memory',
  'author': 842,
  'title': "My mother's handwriting",
  'body': "I found a grocery list in my mother's handwriting tucked in an old coat. Just eggs, "
          'bread, oranges. I stood in the hallway and cried over oranges. The ordinary things are '
          'the ones that ambush you.'},
 {'prompt': "What's on your mind right now?",
  'cat': 'Confession',
  'author': 1999,
  'title': "I'm scared of wasting it",
  'body': "Sometimes I'm so afraid of wasting my life that I freeze and waste the afternoon. I'm "
          'trying to forgive myself for the days I just survive instead of seize. Showing up is '
          'its own kind of brave.'},
 {'prompt': "What's something you've been quietly proud of?",
  'cat': 'Reflection',
  'author': 365,
  'title': 'Proud of a quiet no',
  'body': "I said no to something I'd usually say yes to out of guilt, and the world didn't end. "
          "I'm quietly proud of the boundary. It felt like betrayal in the moment and like "
          'self-respect by evening.'},
 {'prompt': "What's something you've been quietly proud of?",
  'cat': 'Gratitude',
  'author': 1142,
  'title': 'Still here',
  'body': "I'm proud that I'm still here, honestly. A year ago I wasn't sure I would be. Nobody "
          "handed me a trophy for it, but I know what it cost, and that's enough."},
 {'prompt': "What's something you wish you could tell a stranger?",
  'cat': 'Confession',
  'author': 503,
  'title': 'What I never said',
  'body': "I wish I could tell a stranger that I miss someone I'm not allowed to miss anymore. "
          "Saying it to you, who'll never know me, somehow makes it lighter to carry."},
 {'prompt': "What's something you're still learning to forgive?",
  'cat': 'Reflection',
  'author': 778,
  'title': 'Forgiving the younger me',
  'body': "I'm still learning to forgive the version of me who didn't know better. He was just "
          'scared and doing his best with what he had. I think healing is partly letting the past '
          'be young and unfinished.'},
 {'prompt': "What's something you're still learning to forgive?",
  'cat': 'Hope',
  'author': 1688,
  'title': "The grudge I'm setting down",
  'body': "I've carried a grudge so long it started to feel like part of me. I'm not ready to "
          'forgive completely, but today I loosened my grip a little. Even that felt like setting '
          'down a heavy bag.'},
 {'prompt': 'When did you last feel truly at peace?',
  'cat': 'Memory',
  'author': 294,
  'title': 'Peace by the water',
  'body': 'The last time I felt truly at peace was on a dock at dusk, feet in cold lake water, no '
          "phone, no plan. I keep trying to recreate it and forgetting that peace isn't a place — "
          "it's the moment you stop reaching for the next one."}]

SAMPLE_WINS = [{'id': 'w1',
  'text': 'Had a great cup of coffee this morning.',
  'date': 'May 21',
  'likes': 12,
  'liked': False,
  'private': False,
  'comments': [{'id': 'c1a', 'author': 438, 'text': 'Small rituals are everything.'},
               {'id': 'c1b', 'author': 1207, 'text': 'This made me go make one too ☕'}]},
 {'id': 'w2',
  'text': 'Got a kind message from a friend out of the blue.',
  'date': 'May 20',
  'likes': 24,
  'liked': True,
  'private': False,
  'comments': [{'id': 'c2a', 'author': 89, 'text': 'Those are the best kind of days.'}]},
 {'id': 'w3',
  'text': "Finished a task I've been putting off. Feels good!",
  'date': 'May 19',
  'likes': 8,
  'liked': False,
  'private': False,
  'comments': []},
 {'id': 'w4',
  'text': 'Took a walk outside and enjoyed the sunshine.',
  'date': 'May 18',
  'likes': 17,
  'liked': False,
  'private': False,
  'comments': [{'id': 'c4a', 'author': 842, 'text': 'The sun was unreal yesterday.'},
               {'id': 'c4b', 'author': 365, 'text': 'Needed this reminder to step outside.'}]},
 {'id': 'w5',
  'text': 'Watched a movie that made me smile.',
  'date': 'May 17',
  'likes': 5,
  'liked': False,
  'private': True,
  'comments': []}]


def handle_from_number(n: int) -> str:
    """Mirror of handleFromNumber in src/pondr/data.js."""
    return ADJECTIVES[n % len(ADJECTIVES)] + " " + CREATURES[(n * 7) % len(CREATURES)]
